name: 'Setup wasixcc'
description: 'Install wasixcc C/C++ compiler for the WASIX platform with optional toolchain components'
author: 'wasix-org'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  version:
    description: 'Version of wasixcc to install (e.g., v0.2.4, latest). Defaults to latest release.'
    required: false
    default: 'latest'
  
  github_token:
    description: 'GitHub token for API requests and downloads. Pass github.token or secrets.GITHUB_TOKEN'
    required: false
    default: ''
  
  sysroot-tag:
    description: 'Tag of wasix-libc sysroot to install (e.g., v2025-01-01.1, latest).'
    required: false
    default: 'latest'
  
  llvm-tag:
    description: 'Tag of LLVM toolchain to install (e.g., v2025-01-01.1, latest).'
    required: false
    default: 'latest'
  
  binaryen-tag:
    description: 'Tag/version of binaryen to install (e.g., version_118, latest).'
    required: false
    default: 'latest'
  
  install-sysroot:
    description: 'Whether to install the WASIX sysroot (true/false)'
    required: false
    default: 'true'
  
  install-llvm:
    description: 'Whether to install the LLVM toolchain (true/false)'
    required: false
    default: 'true'
  
  install-binaryen:
    description: 'Whether to install binaryen (wasm-opt) (true/false)'
    required: false
    default: 'true'
  
  add-binaryen-path:
    description: 'Whether to add binaryen (wasm-opt) to PATH (true/false)'
    required: false
    default: 'true'
  
  add-llvm-path:
    description: 'Whether to add LLVM toolchain (clang, llvm-ar, etc.) to PATH (true/false)'
    required: false
    default: 'false'

outputs:
  wasixcc-path:
    description: 'Path to the wasixcc executable'
    value: ${{ steps.install-wasixcc.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Ensure required tools are available
      shell: sh
      run: |
        echo "Checking for required tools (curl, sed)..."
        
        # Check if curl is available
        if ! command -v curl >/dev/null 2>&1; then
          echo "curl not found, attempting to install..."
          if command -v apk >/dev/null 2>&1; then
            apk add --no-cache curl
          elif command -v apt-get >/dev/null 2>&1; then
            apt-get update && apt-get install -y curl
          elif command -v pacman >/dev/null 2>&1; then
            pacman -Sy --noconfirm curl
          elif command -v brew >/dev/null 2>&1; then
            brew install curl
          else
            echo "Error: curl is not installed and no supported package manager found"
            exit 1
          fi
        fi
        
        # Check if sed is available
        if ! command -v sed >/dev/null 2>&1; then
          echo "sed not found, attempting to install..."
          if command -v apk >/dev/null 2>&1; then
            apk add --no-cache sed
          elif command -v apt-get >/dev/null 2>&1; then
            apt-get update && apt-get install -y sed
          elif command -v pacman >/dev/null 2>&1; then
            pacman -Sy --noconfirm sed
          elif command -v brew >/dev/null 2>&1; then
            brew install gnu-sed
          else
            echo "Error: sed is not installed and no supported package manager found"
            exit 1
          fi
        fi
        
        echo "Required tools are available"
    
    - name: Detect platform
      id: platform
      shell: sh
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        
        # Normalize OS
        case "$OS" in linux*) OS="linux";; darwin*) OS="apple";; mingw*|msys*|cygwin*|windows*) OS="windows";; *) echo "Unsupported OS: $OS"; exit 1;; esac
        
        # Normalize architecture
        case "$ARCH" in x86_64|amd64) ARCH="x86_64";; aarch64|arm64) ARCH="aarch64";; *) echo "Unsupported architecture: $ARCH"; exit 1;; esac
        
        # Construct target triple
        if [ "$OS" = "linux" ]; then
          if [ -f /lib/ld-musl-x86_64.so.1 ] || [ -f /lib/ld-musl-aarch64.so.1 ] || (ldd --version 2>&1 | grep -qi musl); then
            TARGET="${ARCH}-unknown-linux-musl"
          else
            TARGET="${ARCH}-unknown-linux-gnu"
          fi
        elif [ "$OS" = "apple" ]; then
          TARGET="${ARCH}-apple-darwin"
        elif [ "$OS" = "windows" ]; then
          echo "Warning: Windows builds are not yet available. Please use WSL or a Linux/macOS environment."
          exit 1
        fi
        
        printf "os=%s\n" "$OS" >> $GITHUB_OUTPUT
        printf "arch=%s\n" "$ARCH" >> $GITHUB_OUTPUT
        printf "target=%s\n" "$TARGET" >> $GITHUB_OUTPUT
        echo "Detected platform: $TARGET"

    - name: Resolve wasixcc version
      id: resolve-version
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          echo "Fetching latest release version..."
          if [ -n "$GITHUB_TOKEN" ]; then
            VERSION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/wasix-org/wasixcc/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          else
            VERSION=$(curl -s https://api.github.com/repos/wasix-org/wasixcc/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          fi
          if [ -z "$VERSION" ]; then
            echo "Failed to fetch latest version"
            exit 1
          fi
          echo "Latest version: $VERSION"
        fi
        printf "version=%s\n" "$VERSION" >> $GITHUB_OUTPUT

    - name: Download wasixcc binary
      id: download
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        VERSION="${{ steps.resolve-version.outputs.version }}"
        TARGET="${{ steps.platform.outputs.target }}"
        DOWNLOAD_URL="https://github.com/wasix-org/wasixcc/releases/download/${VERSION}/wasixcc-${TARGET}.tar.gz"
        
        echo "Downloading wasixcc from: $DOWNLOAD_URL"
        if [ -n "$GITHUB_TOKEN" ]; then
          curl -L -H "Authorization: token $GITHUB_TOKEN" -o wasixcc.tar.gz "$DOWNLOAD_URL"
        else
          curl -L -o wasixcc.tar.gz "$DOWNLOAD_URL"
        fi
        
        if [ ! -f wasixcc.tar.gz ]; then
          echo "Failed to download wasixcc"
          exit 1
        fi
        
        echo "Downloaded wasixcc successfully"

    - name: Install wasixcc
      id: install-wasixcc
      shell: sh
      run: |
        echo "Extracting wasixcc..."
        tar -xzf wasixcc.tar.gz
        rm wasixcc.tar.gz
        
        # Create installation directory for the main wasixcc binary
        WASIXCC_HOME="$HOME/.wasixcc"
        mkdir -p "$WASIXCC_HOME"
        
        # Create bin directory for executables installed by --install-executables
        INSTALL_DIR="$WASIXCC_HOME/bin"
        mkdir -p "$INSTALL_DIR"
        
        # Move binary to .wasixcc (not bin) to avoid --install-executables overwriting it
        if [ "${{ steps.platform.outputs.os }}" = "windows" ]; then
          mv wasixcc.exe "$WASIXCC_HOME/"
          WASIXCC_PATH="$WASIXCC_HOME/wasixcc.exe"
        else
          mv wasixcc "$WASIXCC_HOME/"
          chmod +x "$WASIXCC_HOME/wasixcc"
          WASIXCC_PATH="$WASIXCC_HOME/wasixcc"
        fi
        
        # Add bin directory to PATH
        printf "%s\n" "$INSTALL_DIR" >> $GITHUB_PATH
        
        # Install executables (wasix++, wasixar, etc.) to bin directory
        echo "Installing wasixcc executables..."
        "$WASIXCC_PATH" --install-executables "$INSTALL_DIR"
        
        printf "path=%s\n" "$WASIXCC_PATH" >> $GITHUB_OUTPUT
        echo "Installed wasixcc to: $WASIXCC_PATH"
        
        # Verify installation
        "$WASIXCC_PATH" --version

    - name: Install binaryen
      if: inputs.install-binaryen == 'true'
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Installing binaryen (wasm-opt)..."
        BINARYEN_TAG="${{ inputs.binaryen-tag }}"
        
        if [ "$BINARYEN_TAG" = "latest" ]; then
          "$HOME/.wasixcc/wasixcc" --download-binaryen
        else
          "$HOME/.wasixcc/wasixcc" --download-binaryen "$BINARYEN_TAG"
        fi
        
        echo "Installed binaryen successfully"
    
    - name: Add binaryen to PATH
      if: inputs.install-binaryen == 'true' && inputs.add-binaryen-path == 'true'
      shell: sh
      run: |
        # Find binaryen installation directory
        BINARYEN_DIR=$(find "$HOME/.wasixcc" -type d -name "binaryen-*" | head -n 1)
        if [ -n "$BINARYEN_DIR" ] && [ -d "$BINARYEN_DIR/bin" ]; then
          printf "%s\n" "$BINARYEN_DIR/bin" >> $GITHUB_PATH
          echo "Added binaryen to PATH: $BINARYEN_DIR/bin"
        else
          echo "Warning: Could not find binaryen installation directory"
        fi

    - name: Install WASIX sysroot
      if: inputs.install-sysroot == 'true'
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Installing WASIX sysroot..."
        SYSROOT_TAG="${{ inputs.sysroot-tag }}"
        
        if [ "$SYSROOT_TAG" = "latest" ]; then
          "$HOME/.wasixcc/wasixcc" --download-sysroot
        else
          "$HOME/.wasixcc/wasixcc" --download-sysroot "$SYSROOT_TAG"
        fi
        
        echo "Installed WASIX sysroot successfully"

    - name: Install LLVM toolchain
      if: inputs.install-llvm == 'true'
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Installing LLVM toolchain..."
        LLVM_TAG="${{ inputs.llvm-tag }}"
        
        if [ "$LLVM_TAG" = "latest" ]; then
          "$HOME/.wasixcc/wasixcc" --download-llvm
        else
          "$HOME/.wasixcc/wasixcc" --download-llvm "$LLVM_TAG"
        fi
        
        echo "Installed LLVM toolchain successfully"
    
    - name: Add LLVM toolchain to PATH
      if: inputs.install-llvm == 'true' && inputs.add-llvm-path == 'true'
      shell: sh
      run: |
        # Find LLVM installation directory
        LLVM_DIR=$(find "$HOME/.wasixcc" -type d -name "llvm-*" | head -n 1)
        if [ -n "$LLVM_DIR" ] && [ -d "$LLVM_DIR/bin" ]; then
          printf "%s\n" "$LLVM_DIR/bin" >> $GITHUB_PATH
          echo "Added LLVM toolchain to PATH: $LLVM_DIR/bin"
        else
          echo "Warning: Could not find LLVM installation directory"
        fi

    - name: Verify installation
      shell: sh
      run: |
        echo "Verifying installation..."
        echo "wasixcc version:"
        wasixcc --version
        
        echo "Installation complete!"
