name: 'Setup wasixcc'
description: 'Install wasixcc C/C++ compiler for the WASIX platform with optional toolchain components'
author: 'wasix-org'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  version:
    description: 'Version of wasixcc to install (e.g., v0.2.4, latest). Defaults to latest release.'
    required: false
    default: 'latest'
  
  github_token:
    description: 'GitHub token for API requests and downloads. Defaults to github.token if not provided.'
    required: false
    default: ${{ github.token }}
  
  sysroot-tag:
    description: 'Tag of wasix-libc sysroot to install (e.g., v2025-01-01.1, latest).'
    required: false
    default: 'latest'
  
  llvm-tag:
    description: 'Tag of LLVM toolchain to install (e.g., v2025-01-01.1, latest).'
    required: false
    default: 'latest'
  
  binaryen-tag:
    description: 'Tag/version of binaryen to install (e.g., version_118, latest).'
    required: false
    default: 'latest'
  
  install-sysroot:
    description: 'Whether to install the WASIX sysroot (true/false)'
    required: false
    default: 'true'
  
  install-llvm:
    description: 'Whether to install the LLVM toolchain (true/false)'
    required: false
    default: 'true'
  
  install-binaryen:
    description: 'Whether to install binaryen (wasm-opt) (true/false)'
    required: false
    default: 'true'

outputs:
  wasixcc-path:
    description: 'Path to the wasixcc executable'
    value: ${{ steps.install-wasixcc.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Detect platform
      id: platform
      shell: bash
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        
        # Normalize OS
        case "$OS" in linux*) OS="linux";; darwin*) OS="apple";; mingw*|msys*|cygwin*) OS="windows";; *) echo "Unsupported OS: $OS"; exit 1;; esac
        
        # Normalize architecture
        case "$ARCH" in x86_64|amd64) ARCH="x86_64";; aarch64|arm64) ARCH="aarch64";; *) echo "Unsupported architecture: $ARCH"; exit 1;; esac
        
        # Construct target triple
        if [ "$OS" = "linux" ]; then
          if [ -f /lib/ld-musl-x86_64.so.1 ] || [ -f /lib/ld-musl-aarch64.so.1 ] || (ldd --version 2>&1 | grep -qi musl); then
            TARGET="${ARCH}-unknown-linux-musl"
          else
            TARGET="${ARCH}-unknown-linux-gnu"
          fi
        elif [ "$OS" = "apple" ]; then
          TARGET="${ARCH}-apple-darwin"
        else
          TARGET="${ARCH}-pc-windows-msvc"
        fi
        
        echo "os=$OS" >> $GITHUB_OUTPUT
        echo "arch=$ARCH" >> $GITHUB_OUTPUT
        echo "target=$TARGET" >> $GITHUB_OUTPUT
        echo "Detected platform: $TARGET"

    - name: Resolve wasixcc version
      id: resolve-version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          echo "Fetching latest release version..."
          VERSION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/wasix-org/wasixcc/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          if [ -z "$VERSION" ]; then
            echo "Failed to fetch latest version"
            exit 1
          fi
          echo "Latest version: $VERSION"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Download wasixcc binary
      id: download
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        VERSION="${{ steps.resolve-version.outputs.version }}"
        TARGET="${{ steps.platform.outputs.target }}"
        DOWNLOAD_URL="https://github.com/wasix-org/wasixcc/releases/download/${VERSION}/wasixcc-${TARGET}.tar.gz"
        
        echo "Downloading wasixcc from: $DOWNLOAD_URL"
        curl -L -H "Authorization: token $GITHUB_TOKEN" -o wasixcc.tar.gz "$DOWNLOAD_URL"
        
        if [ ! -f wasixcc.tar.gz ]; then
          echo "Failed to download wasixcc"
          exit 1
        fi
        
        echo "Downloaded wasixcc successfully"

    - name: Install wasixcc
      id: install-wasixcc
      shell: bash
      run: |
        echo "Extracting wasixcc..."
        tar -xzf wasixcc.tar.gz
        rm wasixcc.tar.gz
        
        # Create installation directory for the main wasixcc binary
        WASIXCC_HOME="$HOME/.wasixcc"
        mkdir -p "$WASIXCC_HOME"
        
        # Create bin directory for executables installed by --install-executables
        INSTALL_DIR="$WASIXCC_HOME/bin"
        mkdir -p "$INSTALL_DIR"
        
        # Move binary to .wasixcc (not bin) to avoid --install-executables overwriting it
        if [ "${{ steps.platform.outputs.os }}" = "windows" ]; then
          mv wasixcc.exe "$WASIXCC_HOME/"
          WASIXCC_PATH="$WASIXCC_HOME/wasixcc.exe"
        else
          mv wasixcc "$WASIXCC_HOME/"
          chmod +x "$WASIXCC_HOME/wasixcc"
          WASIXCC_PATH="$WASIXCC_HOME/wasixcc"
        fi
        
        # Add bin directory to PATH
        echo "$INSTALL_DIR" >> $GITHUB_PATH
        
        # Install executables (wasix++, wasixar, etc.) to bin directory
        echo "Installing wasixcc executables..."
        "$WASIXCC_PATH" --install-executables "$INSTALL_DIR"
        
        echo "path=$WASIXCC_PATH" >> $GITHUB_OUTPUT
        echo "Installed wasixcc to: $WASIXCC_PATH"
        
        # Verify installation
        "$WASIXCC_PATH" --version

    - name: Install binaryen
      if: inputs.install-binaryen == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Installing binaryen (wasm-opt)..."
        BINARYEN_TAG="${{ inputs.binaryen-tag }}"
        
        if [ "$BINARYEN_TAG" = "latest" ]; then
          "$HOME/.wasixcc/wasixcc" --download-binaryen
        else
          "$HOME/.wasixcc/wasixcc" --download-binaryen "$BINARYEN_TAG"
        fi
        
        echo "Installed binaryen successfully"

    - name: Install WASIX sysroot
      if: inputs.install-sysroot == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Installing WASIX sysroot..."
        SYSROOT_TAG="${{ inputs.sysroot-tag }}"
        
        if [ "$SYSROOT_TAG" = "latest" ]; then
          "$HOME/.wasixcc/wasixcc" --download-sysroot
        else
          "$HOME/.wasixcc/wasixcc" --download-sysroot "$SYSROOT_TAG"
        fi
        
        echo "Installed WASIX sysroot successfully"

    - name: Install LLVM toolchain
      if: inputs.install-llvm == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "Installing LLVM toolchain..."
        LLVM_TAG="${{ inputs.llvm-tag }}"
        
        if [ "$LLVM_TAG" = "latest" ]; then
          "$HOME/.wasixcc/wasixcc" --download-llvm
        else
          "$HOME/.wasixcc/wasixcc" --download-llvm "$LLVM_TAG"
        fi
        
        echo "Installed LLVM toolchain successfully"

    - name: Verify installation
      shell: bash
      run: |
        echo "Verifying installation..."
        echo "wasixcc version:"
        wasixcc --version
        
        echo "Installation complete!"
